version: '3.7'

services:
  searxng:
    container_name: searxng-simple
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
      - SEARXNG_SECRET_KEY=ad2dba6794f775bf4e00732df20d65d5da22bdc2f0a83af7c15c8beb33e10f25
    networks:
      - searxng

networks:
  searxng:
    driver: bridge