# Backend-only build configuration
[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "npm ci --omit=dev",
  "pip3 install requests beautifulsoup4 --break-system-packages"
]

[phases.build]
# Skip build phase - backend doesn't need building
cmds = []

[start]
cmd = "node server/index.js"
