# Backend-only build configuration
[providers]
# Enable both Node.js and Python providers
"..." = ["...", "python"]

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --omit=dev"]

[phases.build]
# Skip build phase - backend doesn't need building
cmds = []

[start]
cmd = "node server/index.js"
