# Backend-only build configuration
[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.requests", "python311Packages.beautifulsoup4"]

[phases.install]
cmds = ["npm ci --omit=dev"]

[phases.build]
# Skip build phase - backend doesn't need building
cmds = []

[start]
cmd = "node server/index.js"
