# Backend-only build configuration
[phases.setup]
nixPkgs = ["nodejs_20", "python311"]

[phases.install]
cmds = [
  "npm ci --omit=dev",
  "python3 -m pip install --user requests beautifulsoup4"
]

[phases.build]
# Skip build phase - backend doesn't need building
cmds = []

[start]
cmd = "node server/index.js"
